export type TarotCard = { id: string; name: string; image: string };

export const tarotCards: TarotCard[] = [
  { id: "o-louco", name: "O Louco", image: "/assets/tarot/o-louco.webp" },
  { id: "o-mago", name: "O Mago", image: "/assets/tarot/o-mago.webp" },
  { id: "a-sacerdotisa", name: "A Sacerdotisa", image: "/assets/tarot/a-sacerdotisa.webp" },
  { id: "a-imperatriz", name: "A Imperatriz", image: "/assets/tarot/a-imperatriz.webp" },
  { id: "o-imperador", name: "O Imperador", image: "/assets/tarot/o-imperador.webp" },
  { id: "o-hierofante", name: "O Hierofante", image: "/assets/tarot/o-hierofante.webp" },
  { id: "os-enamorados", name: "Os Enamorados", image: "/assets/tarot/os-enamorados.webp" },
  { id: "o-carro", name: "O Carro", image: "/assets/tarot/o-carro.webp" },
  { id: "a-forca", name: "A Força", image: "/assets/tarot/a-forca.webp" },
  { id: "o-eremita", name: "O Eremita", image: "/assets/tarot/o-eremita.webp" },
  { id: "a-roda-da-fortuna", name: "A Roda da Fortuna", image: "/assets/tarot/a-roda-da-fortuna.webp" },
  { id: "a-justica", name: "A Justiça", image: "/assets/tarot/a-justica.webp" },
  { id: "o-enforcado", name: "O Enforcado", image: "/assets/tarot/o-enforcado.webp" },
  { id: "a-morte", name: "A Morte", image: "/assets/tarot/a-morte.webp" },
  { id: "a-temperanca", name: "A Temperança", image: "/assets/tarot/a-temperanca.webp" },
  { id: "o-diabo", name: "O Diabo", image: "/assets/tarot/o-diabo.webp" },
  { id: "a-torre", name: "A Torre", image: "/assets/tarot/a-torre.webp" },
  { id: "a-estrela", name: "A Estrela", image: "/assets/tarot/a-estrela.webp" },
  { id: "a-lua", name: "A Lua", image: "/assets/tarot/a-lua.webp" },
  { id: "o-sol", name: "O Sol", image: "/assets/tarot/o-sol.webp" },
  { id: "o-julgamento", name: "O Julgamento", image: "/assets/tarot/o-julgamento.webp" },
  { id: "o-mundo", name: "O Mundo", image: "/assets/tarot/o-mundo.webp" },
  { id: "as-de-paus", name: "Ás de Paus", image: "/assets/tarot/as-de-paus.webp" },
  { id: "dois-de-paus", name: "Dois de Paus", image: "/assets/tarot/dois-de-paus.webp" },
  { id: "tres-de-paus", name: "Três de Paus", image: "/assets/tarot/tres-de-paus.webp" },
  { id: "quatro-de-paus", name: "Quatro de Paus", image: "/assets/tarot/quatro-de-paus.webp" },
  { id: "cinco-de-paus", name: "Cinco de Paus", image: "/assets/tarot/cinco-de-paus.webp" },
  { id: "seis-de-paus", name: "Seis de Paus", image: "/assets/tarot/seis-de-paus.webp" },
  { id: "sete-de-paus", name: "Sete de Paus", image: "/assets/tarot/sete-de-paus.webp" },
  { id: "oito-de-paus", name: "Oito de Paus", image: "/assets/tarot/oito-de-paus.webp" },
  { id: "nove-de-paus", name: "Nove de Paus", image: "/assets/tarot/nove-de-paus.webp" },
  { id: "dez-de-paus", name: "Dez de Paus", image: "/assets/tarot/dez-de-paus.webp" },
  { id: "pajem-de-paus", name: "Pajem de Paus", image: "/assets/tarot/pajem-de-paus.webp" },
  { id: "cavaleiro-de-paus", name: "Cavaleiro de Paus", image: "/assets/tarot/cavaleiro-de-paus.webp" },
  { id: "rainha-de-paus", name: "Rainha de Paus", image: "/assets/tarot/rainha-de-paus.webp" },
  { id: "rei-de-paus", name: "Rei de Paus", image: "/assets/tarot/rei-de-paus.webp" },
  { id: "as-de-copas", name: "Ás de Copas", image: "/assets/tarot/as-de-copas.webp" },
  { id: "dois-de-copas", name: "Dois de Copas", image: "/assets/tarot/dois-de-copas.webp" },
  { id: "tres-de-copas", name: "Três de Copas", image: "/assets/tarot/tres-de-copas.webp" },
  { id: "quatro-de-copas", name: "Quatro de Copas", image: "/assets/tarot/quatro-de-copas.webp" },
  { id: "cinco-de-copas", name: "Cinco de Copas", image: "/assets/tarot/cinco-de-copas.webp" },
  { id: "seis-de-copas", name: "Seis de Copas", image: "/assets/tarot/seis-de-copas.webp" },
  { id: "sete-de-copas", name: "Sete de Copas", image: "/assets/tarot/sete-de-copas.webp" },
  { id: "oito-de-copas", name: "Oito de Copas", image: "/assets/tarot/oito-de-copas.webp" },
  { id: "nove-de-copas", name: "Nove de Copas", image: "/assets/tarot/nove-de-copas.webp" },
  { id: "dez-de-copas", name: "Dez de Copas", image: "/assets/tarot/dez-de-copas.webp" },
  { id: "pajem-de-copas", name: "Pajem de Copas", image: "/assets/tarot/pajem-de-copas.webp" },
  { id: "cavaleiro-de-copas", name: "Cavaleiro de Copas", image: "/assets/tarot/cavaleiro-de-copas.webp" },
  { id: "rainha-de-copas", name: "Rainha de Copas", image: "/assets/tarot/rainha-de-copas.webp" },
  { id: "rei-de-copas", name: "Rei de Copas", image: "/assets/tarot/rei-de-copas.webp" },
  { id: "as-de-espadas", name: "Ás de Espadas", image: "/assets/tarot/as-de-espadas.webp" },
  { id: "dois-de-espadas", name: "Dois de Espadas", image: "/assets/tarot/dois-de-espadas.webp" },
  { id: "tres-de-espadas", name: "Três de Espadas", image: "/assets/tarot/tres-de-espadas.webp" },
  { id: "quatro-de-espadas", name: "Quatro de Espadas", image: "/assets/tarot/quatro-de-espadas.webp" },
  { id: "cinco-de-espadas", name: "Cinco de Espadas", image: "/assets/tarot/cinco-de-espadas.webp" },
  { id: "seis-de-espadas", name: "Seis de Espadas", image: "/assets/tarot/seis-de-espadas.webp" },
  { id: "sete-de-espadas", name: "Sete de Espadas", image: "/assets/tarot/sete-de-espadas.webp" },
  { id: "oito-de-espadas", name: "Oito de Espadas", image: "/assets/tarot/oito-de-espadas.webp" },
  { id: "nove-de-espadas", name: "Nove de Espadas", image: "/assets/tarot/nove-de-espadas.webp" },
  { id: "dez-de-espadas", name: "Dez de Espadas", image: "/assets/tarot/dez-de-espadas.webp" },
  { id: "pajem-de-espadas", name: "Pajem de Espadas", image: "/assets/tarot/pajem-de-espadas.webp" },
  { id: "cavaleiro-de-espadas", name: "Cavaleiro de Espadas", image: "/assets/tarot/cavaleiro-de-espadas.webp" },
  { id: "rainha-de-espadas", name: "Rainha de Espadas", image: "/assets/tarot/rainha-de-espadas.webp" },
  { id: "rei-de-espadas", name: "Rei de Espadas", image: "/assets/tarot/rei-de-espadas.webp" },
  { id: "as-de-ouros", name: "Ás de Ouros", image: "/assets/tarot/as-de-ouros.webp" },
  { id: "dois-de-ouros", name: "Dois de Ouros", image: "/assets/tarot/dois-de-ouros.webp" },
  { id: "tres-de-ouros", name: "Três de Ouros", image: "/assets/tarot/tres-de-ouros.webp" },
  { id: "quatro-de-ouros", name: "Quatro de Ouros", image: "/assets/tarot/quatro-de-ouros.webp" },
  { id: "cinco-de-ouros", name: "Cinco de Ouros", image: "/assets/tarot/cinco-de-ouros.webp" },
  { id: "seis-de-ouros", name: "Seis de Ouros", image: "/assets/tarot/seis-de-ouros.webp" },
  { id: "sete-de-ouros", name: "Sete de Ouros", image: "/assets/tarot/sete-de-ouros.webp" },
  { id: "oito-de-ouros", name: "Oito de Ouros", image: "/assets/tarot/oito-de-ouros.webp" },
  { id: "nove-de-ouros", name: "Nove de Ouros", image: "/assets/tarot/nove-de-ouros.webp" },
  { id: "dez-de-ouros", name: "Dez de Ouros", image: "/assets/tarot/dez-de-ouros.webp" },
  { id: "pajem-de-ouros", name: "Pajem de Ouros", image: "/assets/tarot/pajem-de-ouros.webp" },
  { id: "cavaleiro-de-ouros", name: "Cavaleiro de Ouros", image: "/assets/tarot/cavaleiro-de-ouros.webp" },
  { id: "rainha-de-ouros", name: "Rainha de Ouros", image: "/assets/tarot/rainha-de-ouros.webp" },
  { id: "rei-de-ouros", name: "Rei de Ouros", image: "/assets/tarot/rei-de-ouros.webp" },
];
